export default [
    "Abn Amro Bank Colombia",
    "Alianza Fiduciaria",
    "AV Villas",
    "Bancafé",
    "Banco Agrario",
    "Banco Caja Social",
    "Banco De Bogotá",
    "Banco De Crédito",
    "Banco De Occidente",
    "Banco Finandina",
    "Banco GNB Sudameris",
    "Banco Mercantil De Colombia",
    "Banco Pichincha",
    "Banco Popular",
    "Banco Procredit",
    "Banco Santander",
    "Bancolombia",
    "Bancoomeva",
    "BBVA",
    "BBVA Colombia",
    "Citibank",
    "Colmena BCSC",
    "Colpatria",
    "Confiar",
    "Coomeva",
    "Coopcentral",
    "Cooperativa Financiera de Antioquia",
    "Corficolombiana",
    "Corpbanca",
    "Cotrafa Cooperativa Financiera",
    "Davivienda",
    "Falabella",
    "Financiera Juriscoop",
    "Gran Banco Bancafe",
    "Granahorrar (BBVA)",
    "Helm Bank",
    "banco",
    "Helm",
    "banco",
    "Helm Trust",
    "HSBC",
    "Intercontinental",
    "JP Morgan",
    "RBS",
    "Skandia",
    "Skotiabank Colombia",
    "Sudameris",
    "Ya Servicios Financieros",
    "Otro"
]
